In [1]:
import requests
from bs4 import BeautifulSoup
url="https://www.politifact.com/"
response=requests.get(url)#step-1
#print(response.status_code)
response=response.text#step-2
soup=BeautifulSoup(response,"html.parser")#step-3
#print(soup)
#print(soup.prettify)

source=[]
statement=[]
link=[]
date=[]
d1=[]
a=soup.find("div",class_="embla")
b=soup.find_all("div",class_="embla__slide caro-listing__item")
for i in b:
    post=i.find("div",class_="m-statement__meta").find("a").text.strip()
    source.append(post)
    s=i.find("div",class_="m-statement__quote").find("a").text.strip()
    statement.append(s)
    l=i.find("div",class_="m-statement__quote").find("a")["href"]
    link.append("https://www.politifact.com"+l)
    d=i.find("div",class_="m-statement__desc").text.strip()
    l_d=d.split()
    l1=(" ".join(l_d[2:5]))
    date.append(l1)

import pandas as pd
df=pd.DataFrame({"source":source,"statement":statement,"link":link,"Date":date,})
df

,source,statement,link,Date
0,X posts,"Video shows U.S. Rep. Byron Donalds saying, “I...",https://www.politifact.com/factchecks/2026/may...,"May 14, 2026"
1,X posts,An American passenger on the cruise ship invol...,https://www.politifact.com/factchecks/2026/may...,"May 6, 2026"
2,Marcy Kaptur,Republicans “want you to pay $1 Billion for a ...,https://www.politifact.com/factchecks/2026/may...,"May 5, 2026"
3,X posts,“California only has ‘enough’ oil and gas supp...,https://www.politifact.com/factchecks/2026/may...,"May 6, 2026"
4,Restoration of America,“83% of us favor requiring a photo ID to vote....,https://www.politifact.com/factchecks/2026/apr...,"April 13, 2026"
5,Social Media,Video shows a US soldier crying and saying she...,https://www.politifact.com/factchecks/2026/apr...,"April 4, 2026"

# offline web scrapping(most important)

In [2]:
from bs4 import BeautifulSoup
import pandas as pd
website="Certified used Mercedes-Benz for sale.html"
file=open(website,encoding="utf-8")
response=file.read()
soup=BeautifulSoup(response,"html.parser")
# soup=soup.prettify()
# print(soup)

# create dataframe with columns car name,rating,review count,price,dealer name,mileage

In [16]:
import numpy as np
name=[]
mileage=[]
dealer_name=[]
price=[]
review=[]
rating=[]
a=soup.find("div",class_="sds-page-section__content")
b=soup.find_all("div",class_="vehicle-details")
for i in b:
    c=i.find("h2",class_="title").text.strip()
    name.append(c)
    m=i.find("div",class_="mileage").text.strip()
    mileage.append(m)
    d=i.find("div",class_="dealer-name").text.strip()
    dealer_name.append(d)
    p=i.find("span",class_="primary-price").text.strip()
    price.append(p)
    r=i.find("span",class_="sds-rating__link sds-button-link").text.strip()
    review.append(r[1:-9])
    try:
        rat=i.find("span",class_="sds-rating__count").text.strip()
        rating.append(rat)
    except:
        rating.append(np.nan)
df=pd.DataFrame({"Carname":name,"mileage":mileage,"dealername":dealer_name,"price":price,"review":review,"rating":rating})
df

,Carname,mileage,dealername,price,review,rating
0,2020 Mercedes-Benz CLA 250 Base 4MATIC,"28,744 mi.",Mercedes-Benz of Lynnwood,"$35,995",130,4.4
1,2019 Mercedes-Benz AMG GT 53 Base,"25,771 mi.",International Autos,"$79,995",117,4.0
2,2021 Mercedes-Benz AMG GLE 53 Base,"22,374 mi.",John Sisson Motors,"$80,923",38,2.8
3,2022 Mercedes-Benz AMG CLA 45 Base 4MATIC,"10,595 mi.",Mercedes-Benz of Santa Rosa,"$56,633",30,NaN
4,2021 Mercedes-Benz AMG GLE 53 Base,"33,622 mi.",Mercedes-Benz of Rochester,"$76,995",152,4.7
5,2021 Mercedes-Benz E-Class E 450 4MATIC,"12,477 mi.",Benzel-Busch Motor Car,"$76,532","5,283",4.5
6,2021 Mercedes-Benz AMG GLE 63 S-Model 4MATIC,"22,383 mi.",Mercedes-Benz of Lancaster,"$102,990",174,4.8
7,2019 Mercedes-Benz S-Class S 560,"49,332 mi.",Mercedes-Benz of Ontario,"$54,580","2,016",4.8
8,2021 Mercedes-Benz AMG GLE 53 Base,"37,688 mi.",John Sisson Motors,"$76,715",38,2.8
9,2021 Mercedes-Benz GLA 250 Base,"19,521 mi.",Mercedes-Benz of Augusta,"$34,999",264,4.6
10,2022 Mercedes-Benz AMG C 43 Base 4MATIC,"14,420 mi.",Mercedes-Benz of Chicago,"$62,991","1,327",4.8
11,2018 Mercedes-Benz AMG C 43 Base 4MATIC,"34,555 mi.",Mercedes-Benz of South Orlando,"$39,999","1,388",4.4
12,2021 Mercedes-Benz E-Class E 450 4MATIC,"16,474 mi.",Contemporary Motor Cars Inc.,"$74,998",226,4.8
13,2021 Mercedes-Benz S-Class S 580 4MATIC,"10,233 mi.",Mercedes-Benz of Fort Washington,"$99,822","2,788",4.5
14,2022 Mercedes-Benz GLE 450 AWD 4MATIC,"6,800 mi.",Mercedes-Benz of Chicago,"$73,990","1,327",4.8
15,2018 Mercedes-Benz GLC 300 Base 4MATIC,"54,467 mi.",Mercedes-Benz of Fort Washington,"$29,151","2,788",4.5
16,2022 Mercedes-Benz AMG GLA 35 Base,"8,690 mi.",Mercedes-Benz of Fort Washington,"$49,736","2,788",4.5
17,2022 Mercedes-Benz GLB 250 Base,"8,158 mi.",Mercedes-Benz Of Tampa,"$42,000","3,521",4.1
18,2022 Mercedes-Benz S-Class S 500 4MATIC,"8,401 mi.",Mercedes-Benz of Walnut Creek,"$86,986","1,016",4.5
19,2020 Mercedes-Benz AMG S 63 Base 4MATIC,"24,958 mi.",Autobahn Motors,"$105,997","1,000",4.8
20,2021 Mercedes-Benz GLC 300 Base 4MATIC,"49,278 mi.",Bergstrom Luxury on Victory Lane,"$37,280",292,4.2

In [2]:
from bs4 import BeautifulSoup
import pandas as pd
website="30 Most Popular Movies Right Now_ What to Watch In Theaters and Streaming __ Rotten Tomatoes – Movie and TV News.html"
file=open(website,encoding="utf-8")
response=file.read()
soup=BeautifulSoup(response,"html.parser")
movie=[]
rating=[]
director=[]
a=soup.find_all("div",class_="col-sm-18 col-full-xs countdown-item-content")
for i in a:
    movie.append(i.find("h2").find("a").text.strip())
    rating.append(i.find("span",class_="tMeterScore").text.strip())
    director.append(i.find("div",class_="info director").find("a").text.strip())
df=pd.DataFrame({"movie":movie,"rating":rating,"director":director})
df

                                      movie rating               director
0          Transformers: Rise of the Beasts    53%       Steven Caple Jr.
1       Spider-Man: Across the Spider-Verse    96%     Joaquim Dos Santos
2                        The Little Mermaid    67%           Rob Marshall
3                             The Boogeyman    63%             Rob Savage
4     Are You There God? It's Me, Margaret.    99%     Kelly Fremon Craig
5                                    Fast X    56%        Louis Leterrier
6                                BlackBerry    98%           Matt Johnson
7                               The Machine    27%          Peter Atencio
8                                   Reality    92%            Tina Satter
9                               Flamin' Hot    68%           Eva Longoria
10           Guardians of the Galaxy Vol. 3    82%             James Gunn
11                                Blue Jean    94%         Georgia Oakley
12                               Past Lives    97%            Celine Song
13              The Super Mario Bros. Movie    58%          Aaron Horvath
14                 Avatar: The Way of Water    76%          James Cameron
15               Guy Ritchie's The Covenant    83%            Guy Ritchie
16                                Bumblebee    91%          Travis Knight
17                                Nefarious    33%           Cary Solomon
18                                     Sisu    93%       Jalmari Helander
19                     You Hurt My Feelings    95%      Nicole Holofcener
20                     John Wick: Chapter 4    94%         Chad Stahelski
21                           Leave No Trace    80%           Irene Taylor
22                          About My Father    36%          Laura Terruso
23  Dungeons & Dragons: Honor Among Thieves    90%  Jonathan M. Goldstein
24                             Transformers    57%            Michael Bay
25                                 My Fault              Domingo González
26                         A Beautiful Life    50%             Mehdi Avaz
27     The Angry Black Girl and Her Monster    88%        Bomani J. Story
28                                  Missing    87%           Will Merrick
29                                      Air    92%            Ben Affleck

In [33]:
from bs4 import BeautifulSoup
import pandas as pd
website="SENSEX Top Gainers, BSE Daily Top Gainers - Stock Market (1).html"
file=open(website,encoding="utf-8")
response=file.read()
soup=BeautifulSoup(response,"html.parser")
a=soup.find("table")
b=soup.find_all("tr")
company=[]
price=[]
c_date=[]
change=[]
change_pr=[]
day=[]
for i in b[1:]:
    company.append(i.find("td",class_="v-align").text.strip())
    price.append(i.find("td",class_="txt-right v-align").text.strip())
    c_date.append(i.find("td",class_="txt-right no-wrap").find("small").text.strip())
    days=i.find("div",class_="btm clearfix").text.strip()
    d1=days.split("\n")
    d2=d1[0]+" "+d1[1]
    day.append(d2)
    c=i.find_all("td",class_="txt-ctr")
    for i in c[::2]:
        change.append(i.text.strip())
    for i in c[1::2]:
        change_pr.append(i.text.strip())
df=pd.DataFrame({"Company":company,"Current Price":price,"Prev Close Date":c_date,"Change":change,"Change %":change_pr,
                 "	Day's Low/High":day})
df

,Company,Current Price,Prev Close Date,Change,Change %,\tDay's Low/High
0,Tata Motors,583.30,16-06-2023,13.75,2.41%,562.40 584.00
1,HCL Tech.,1168.20,16-06-2023,19.20,1.67%,1130.15 1170.00
2,TCS,3227.20,16-06-2023,51.95,1.64%,3201.60 3232.00
3,Power Grid Corpn.,248.95,16-06-2023,2.85,1.16%,243.25 249.75
4,Infosys,1303.15,16-06-2023,10.50,0.81%,1291.00 1304.40
5,Vedanta,282.60,16-06-2023,2.25,0.80%,278.70 284.35
6,Larsen & Toubro,2382.20,16-06-2023,15.70,0.66%,2355.00 2390.30
7,Bajaj Finance,7247.85,16-06-2023,44.45,0.62%,7202.00 7375.00
8,HDFC Bank,1608.30,16-06-2023,6.20,0.39%,1590.90 1610.95
9,Bajaj Auto,4659.90,16-06-2023,17.15,0.37%,4570.70 4670.80
10,HDFC,2657.85,16-06-2023,6.70,0.25%,2632.00 2663.25
11,ONGC,157.25,16-06-2023,0.35,0.22%,156.60 157.80
12,Asian Paints,3318.40,16-06-2023,3.20,0.10%,3276.30 3326.45
13,Tata Steel,114.30,16-06-2023,0.05,0.04%,113.50 115.25

# rest API(representational state transfer application programming interface)

In [ ]:
import requests,json
city=input("enter city:")
api
url=https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API key}